### ISSUE TITLE
PIP colorama

### ISSUE THREAD

**Issue by dovron** [ynonp/python-examples-verint-2016-07#16]
Hi,
I have installed colorama , but after running the example I cannot see colors...

What I missed?

![image](https://cloud.githubusercontent.com/assets/20268575/16579795/16d147f6-42aa-11e6-859f-325ed173ba04.png)

**Comment by ynonp** [comment]
You didn't send the script. Can you try the following script and let me know if it works (notice the init() call):

from colorama import Fore, Back, Style, init
init()
print(Fore.RED + 'some red text') print(Back.GREEN + 'and with a green background') print(Style.DIM + 'and in dim text') print(Style.RESET_ALL) print('back to normal now')



—
הבלוג שלי מתעדכן פעמיים בשבוע במאמרים מקצועיים מתחום התכנות. מוזמנים לקרוא ולשתף:
https://tocode.co.il/blog

**Comment by ynonp** [comment]
You didn't send the script. Can you try the following script and let me know if it works (notice the init() call):

```
from colorama import Fore, Back, Style, init
init()

print(Fore.RED + 'some red text') 
print(Back.GREEN + 'and with a green background') 
print(Style.DIM + 'and in dim text') 
print(Style.RESET_ALL) 
print('back to normal now')
```

**Comment by dovron** [comment]
Thanks, now it working!

please fix the code in the example..
![image](https://cloud.githubusercontent.com/assets/20268575/16583815/b2fbf3fe-42c0-11e6-9e48-11c14c333896.png)

**Comment by ynonp** [comment]
Fixed. Thanks for the attention!
