### ISSUE TITLE
תרגיל הגשה

### ISSUE THREAD

**Issue by HananRosenthal** [ynonp/python-examples-verint-2016-07#211]
What is the "props" exercise?

**Comment by ynonp** [comment]
Hi Hanan,
There are two exercises to submit this week:
1. Exceptions exercise: https://www.tocode.co.il/bundles/python-verint/lessons/exceptions-lab
2. Final Project (tic tac toe game): https://www.tocode.co.il/bundles/python-verint/lessons/classes-final-lab

**Comment by HananRosenthal** [comment]
i am referring to last week exercises

**Comment by ynonp** [comment]
Last week also had 2 exercises: 

Regular Expressions - https://www.tocode.co.il/bundles/python-verint/lessons/regexp-lab
and Class Syntax - https://www.tocode.co.il/bundles/python-verint/lessons/class-syntax-lab

Which one are you referring to? What's the question about it?

**Comment by HananRosenthal** [comment]
Under regular expressions, submit tab, there are 5 exersices to submit - why?

**Comment by ynonp** [comment]
That was by mistake. Fixed it now. Thanks for the attention.
